spring: 
  application: 
    name: springboot
  mail:
    host: smtp.qq.com
    port: 587
    username: kungzai@qq.com
    password: hmtgrjhxmroubecd
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
  datasource:
    base:
      #监控统计拦截的filters
      filters: stat
      type: com.alibaba.druid.pool.DruidDataSource
      jdbc-url: jdbc:mysql://192.168.2.7:185/ht_micro_record?useUnicode=true&characterEncoding=UTF-8
      username: root
      password: 123456
      driver-class-name: com.mysql.jdbc.Driver
      max-idle: 10
      max-wait: 10000
      min-idle: 5
      initial-size: 5
      validation-query: SELECT 1
      test-on-borrow: false
      test-while-idle: true
      time-between-eviction-runs-millis: 18800
    dic:
      #监控统计拦截的filters
      filters: stat
      type: com.alibaba.druid.pool.DruidDataSource
      jdbc-url: jdbc:mysql://192.168.1.48:3306/ht_nlp?useUnicode=true&characterEncoding=UTF-8&useSSL=false
      username: root
      password: Sonar@1234
      driver-class-name: com.mysql.jdbc.Driver
      max-idle: 10
      max-wait: 10000
      min-idle: 5
      initial-size: 5
      validation-query: SELECT 1
      test-on-borrow: false
      test-while-idle: true
      time-between-eviction-runs-millis: 18800
#    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://127.0.0.1:3306/springboot?characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
#    username: root
#    password:
#    hikari:
#      maximum-pool-size: 20
#      minimum-idle: 5
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
#  data:
#    mongodb:
#      always-use-m-beans: false
#      authentication-database: 'auth_dev '
#      connect-timeout: 10000
#      heartbeat-connect-timeout: 20000
#      heartbeat-frequency: 10000
#      heartbeat-socket-timeout: 20000
#      local-threshold: 15
#      max-connection-idel-time: 0
#      max-connection-life-time: 0
#      max-connections-per-host: 100
#      max-wait-time: 120000
#      min-connections-per-host: 10
#      min-heartbeat-frequency: 500
#      server-selection-timeout: 30000
#      socket-keep-alive: false
#      socket-timeout: 0
#      ssl-enabled: false
#      ssl-invalid-host-name-allowed: false
#      threads-allowed-to-block-for-connection-multiplier: 5
#      uri: mongodb://127.0.0.1:27017/mydb

  main:
    allow-bean-definition-overriding: true

  redis:
    host: 127.0.0.1
    database: 1
    port: 6379
    password: ''
    timeout: 1s
    jedis:
      pool:
        max-active: 20
        max-idle: 20
        min-idle: 10
        max-wait: -1ms
  cache:
    redis:
      use-key-prefix: true
      key-prefix: dev
      cache-null-values: false
      time-to-live: 20s

mongodb:
  primary:
    database: primary
    uri: mongodb://127.0.0.1:27017
  secondary:
    database: secondary
    uri: mongodb://127.0.0.1:27017


com:
  mqtt:
    inbound:
      url: tcp://144.34.177.162:1883
      clientId: ServerIn
      topics: topic_in
      username: admin
      password: public
    outbound:
      urls: tcp://144.34.177.162:1883
      clientId: ServerOut
      topic: topic_out
      username: admin
      password: public

server:
  port: 10000

jwt:
  config:
    key: codewj
    ttl: 3600000

mybatis:
  mapper-locations: classpath:mapper/*.xml

