spring: 
  application: 
    name: springboot
  mail:
    host: smtp.qq.com
    port: 587
    username: kungzai@qq.com
    password: hmtgrjhxmroubecd
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/springboot?characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password:
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    generate-ddl: true
    hibernate:
      ddl-auto: update


  main:
    allow-bean-definition-overriding: true

  redis:
    host: 127.0.0.1
    database: 1
    port: 6379
    password: ''
    timeout: 1s
    jedis:
      pool:
        max-active: 20
        max-idle: 20
        min-idle: 10
        max-wait: -1ms
  cache:
    redis:
      use-key-prefix: true
      key-prefix: dev
      cache-null-values: false
      time-to-live: 20s


com:
  mqtt:
    inbound:
      url: tcp://144.34.177.162:1883
      clientId: ServerIn
      topics: topic_in
      username: admin
      password: public
    outbound:
      urls: tcp://144.34.177.162:1883
      clientId: ServerOut
      topic: topic_out
      username: admin
      password: public

server:
  port: 10000

jwt:
  config:
    key: codewj
    ttl: 3600000

mybatis:
  mapper-locations: classpath:mapper/*.xml